services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - media-server
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:80/health || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 1
      start_period: 15s

networks:
  media-server:
    external: true
