on: push
jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
      - name: Setup Environment Variables
        run: cp .env.example .env
      - name: Validate Docker Compose
        run: docker-compose -f docker-compose.yml config
      - name: Validate Docker Compose (Reverse Proxy)
        run: docker-compose -f docker-compose-rp.yml config
